package fi.thl.thldtkk.api.metadata.domain;

public enum PostStudyRetentionOfPersonalData {
  ARCHIVE,
  DISPOSE,
  DISPOSE_SCIENTIFIC,
  ARCHIVE_WITHOUT_IDENTIFIERS,
  ARCHIVE_WITHOUT_IDENTIFIERS_SCIENTIFIC,
  ARCHIVE_WITH_IDENTIFIERS,
  ARCHIVE_WITH_IDENTIFIERS_SCIENTIFIC
}
