package fi.thl.thldtkk.api.metadata.domain;

public enum PrincipleForDigitalSecurity {
  USERNAME,
  PASSWORD,
  LOGGING,
  PHYSICAL_ACCESS_CONTROL,
  PSEUDONYMIZATION,
  ANONYMIZATION,
  REMOVAL_OF_IDENTIFIABLE_INFORMATION,
  MULTI_FACTOR_AUTHENTICATION,
  ENCRYPTION_OF_INFORMATION,
  OTHER
}
