export enum LegalBasisForHandlingPersonalData {
  CONSENT = 'CONSENT',
  LEGAL_OBLIGATION = 'LEGAL_OBLIGATION',
  DUTY = 'DUTY',
  RESEARCH = 'RESEARCH',
  ARCHIVE = 'ARCHIVE',
  STATISTICS = 'STATISTICS',
  GOVERNMENTAL = 'GOVERNMENTAL',
  OTHER = 'OTHER'
}
