export enum LegalBasisForHandlingSensitivePersonalData {
  CONSENT = 'CONSENT',
  RESEARCH_OR_STATISTICS = 'RESEARCH_OR_STATISTICS',
  MARKED_AS_PUBLIC = 'MARKED_AS_PUBLIC',
  PUBLIC_INTEREST = 'PUBLIC_INTEREST',
  PUBLIC_HEALTH = 'PUBLIC_HEALTH',
  OTHER = 'OTHER'
}
