export enum PostStudyRetentionOfPersonalData {
  ARCHIVE = 'ARCHIVE',
  DISPOSE = 'DISPOSE',
  DISPOSE_SCIENTIFIC = 'DISPOSE_SCIENTIFIC',
  ARCHIVE_WITHOUT_IDENTIFIERS = 'ARCHIVE_WITHOUT_IDENTIFIERS',
  ARCHIVE_WITHOUT_IDENTIFIERS_SCIENTIFIC = 'ARCHIVE_WITHOUT_IDENTIFIERS_SCIENTIFIC',
  ARCHIVE_WITH_IDENTIFIERS = 'ARCHIVE_WITH_IDENTIFIERS',
  ARCHIVE_WITH_IDENTIFIERS_SCIENTIFIC = 'ARCHIVE_WITH_IDENTIFIERS_SCIENTIFIC'
}
