export enum PrincipleForDigitalSecurity {
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  LOGGING = 'LOGGING',
  PHYSICAL_ACCESS_CONTROL = 'PHYSICAL_ACCESS_CONTROL',
  PSEUDONYMIZATION = 'PSEUDONYMIZATION',
  ANONYMIZATION = 'ANONYMIZATION',
  REMOVAL_OF_IDENTIFIABLE_INFORMATION = 'REMOVAL_OF_IDENTIFIABLE_INFORMATION',
  MULTI_FACTOR_AUTHENTICATION = 'MULTI_FACTOR_AUTHENTICATION',
  ENCRYPTION_OF_INFORMATION = 'ENCRYPTION_OF_INFORMATION'
}
