export enum ReceivingGroup {
    RESEARCH_ORGANIZATIONS = "RESEARCH_ORGANIZATIONS",
    COMPANIES = "COMPANIES",
    HEALTHCARE_UNITS = "HEALTHCARE_UNITS",
    SERVICE_PRODUCERS = "SERVICE_PRODUCES",
    OTHER = "OTHER"
  }