export enum RetentionPolicy {
  PERMANENT = "PERMANENT",
  DEFINITE_DURATION = "DEFINITE_DURATION",
  PARTIALLY_PERMANENT_OR_DEFINITE_DURATION = "PARTIALLY_PERMANENT_OR_DEFINITE_DURATION",
  UNDEFINED = "UNDEFINED"
}