export enum StudyFormType {
  DIGITAL = 'DIGITAL',
  PAPER = 'PAPER',
  HUMAN_SAMPLE = 'HUMAN_SAMPLE',
  MICROBE_SAMPLE = 'MICROBE_SAMPLE',
  ENVIRONMENTAL_SAMPLE = 'ENVIRONMENTAL_SAMPLE',
  ANIMAL_SAMPLE = 'ANIMAL_SAMPLE',
  CELL_SAMPLE = 'CELL_SAMPLE'
}
