export enum TypeOfSensitivePersonalData {
  ETHNIC = 'ETHNIC',
  POLITIC = 'POLITIC',
  RELIGIOUS = 'RELIGIOUS',
  PROFESSIONAL_ORGANIZATION_MEMBERSHIP = 'PROFESSIONAL_ORGANIZATION_MEMBERSHIP',
  GENETIC = 'GENETIC',
  BIOMETRIC = 'BIOMETRIC',
  HEALTH = 'HEALTH',
  SEXUAL = 'SEXUAL',
  OTHER = 'OTHER'
}
